backend/src/app/myinfo/dto/profile-modifying-request.dto.ts, backend/src/app/myinfo/exception/username-duplicate.exception.ts, backend/src/app/myinfo/myinfo.controller.ts, backend/src/app/myinfo/myinfo.service.ts, backend/src/app/user/entity/user.entity.ts, backend/src/app/user/user.repository.ts, backend/src/common/decorator/api-success-resposne.decorator.ts, backend/src/common/guard/jwt-auth.guard.ts, backend/src/common/response-entity.ts
- 프로필 수정 API
- 어차피 바뀌는 내용이 없는데 DTO를 그냥 넘기면 안 될까..?
- 팀원과의 합의
- 물론 DTO를 풀어헤쳐서 Service에 넘겨주면 Request에 대한 의존성이 줄어들기 때문에 얻을 수 있는 이점들이 있다. 
- side effect를 줄일 수 있다.
- 같은 경로에서 요청이 바뀌었을 때의 유연성, 확장성을 챙길 수 있다.
- 하지만 위의 이점을 얻을 정도로 중요하지 않거나, 복잡하지 않은 로직에는 DTO를 그냥 전달하는 것이 생산성 측면에서 더 좋지 않을까?
- 엄청 크리티컬한 로직이 아니라면 굳이 풀어헤쳐서 Service에 전달하는 것이 아닌, Request를 그냥 전달하자고 합의했다.
- [DTO의 사용 범위에 대하여 - 원본](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)
- [DTO의 사용 범위에 대하여 - 위 링크의 Nest 버전](https://overcome-the-limits.tistory.com/648)
- `toEntity()` 메소드를 이용해 새로운 인스턴스를 반환해주는 모습이다. 참고할만 하다.
=> [Feature] 프로필 수정 API

backend/sql/category.sql, backend/src/app.module.ts, backend/src/app/group-application/dto/attend-group-request.dto.ts, backend/src/app/group-application/dto/attend-group-response.dto.ts, backend/src/app/group-application/entity/group-application.entity.ts, backend/src/app/group-application/exception/cannot-applicate.exception.ts, backend/src/app/group-application/exception/duplicate-application.exception.ts, backend/src/app/group-application/exception/group-not-found.exception.ts, backend/src/app/group-application/group-application.controller.ts, backend/src/app/group-application/group-application.module.ts, backend/src/app/group-application/group-application.repository.ts, backend/src/app/group-application/group-application.service.ts, backend/src/app/group-application/type/group-application-status.transformer.ts, backend/src/app/group-article/group-article.module.ts, backend/src/app/group-article/repository/group-article.repository.ts, backend/src/app/group-article/repository/group.repository.ts, backend/src/setSwagger.ts
- 모집 신청하기 API 작성
- 예외처리
- 중복 신청
- 글 작성자와 참가신청을 했는지
- 그룹 아이디에 해당하는 그룹이 있는지
- 인덱싱을 어떻게 처리할 지 몰라 검색하고 공부했다.
- 결국 명일 선생님께 여쭤봄
- 인덱싱된 요소를 순서대로 where에 나열하면 옵티마이저에 의해 자동으로 인덱싱을 탄다고 한다.
- 도커 로그로 쿼리문이 생성되는 것을 확인했고, where문에 나열되는 것을 확인할 수 있었다.
=> [Feature] 모집 신청하기 API

backend/src/app/group-article/dto/get-group-chat-url-response.dto.ts, backend/src/app/group-article/exception/not-participant.exception.ts, backend/src/app/group-article/exception/not-success-group.exception.ts, backend/src/app/group-article/group-article.controller.ts, backend/src/app/group-article/group-article.service.ts, backend/src/common/config/database/typeorm/config.service.ts, backend/src/common/guard/jwt-auth.guard.ts
- 모집게시글이 존재하지 않는 경우 `GroupArticleNotFoundException` 반환
- 모집완료된 게시글이 아닌 경우, `NotSuccessGroupException` 반환
- 모임참가자가 아닌 경우 `NotParticipantException` 반환
- 따로 신청정보 + 1로 모임인원 정보를 제공할 수 있지만, 모임참가자 조회시 불편할 것 같아요.
- 신청정보에서 유저 정보들 가져오고, 작성자 유저정보 가져오고 하는게 번거롭다고 느껴졌어요.
- 그래서 작성자의 신청정보를 모집게시글 작성시 추가하도록 했습니다.
기본적으로 mysql 서버의 최대 연결가능수는 151로 설정되어있어요. typeorm을 사용해 mysql과 통신하면 mysql2드라이버를 사용하게 돼요. mysql2에서 기본적인 poolSize는 10이므로 typeorm에서도 10으로 예상돼요. 그래서 connection pool size를 우선 50으로 잡아놨어요. 
- 기존에 엑세스토큰이 쿠키에 없으면 바로 에러를 던지도록 코드가 짜여져있었어요. 하지만 쿠키에 엑세스토큰을 담다보니 만료되면 쿠키가 사라져서 요청에 포함되지 않아요. 이로 인해 리프레시 토큰을 사용한 갱신로직이 동작하지 않았어요.
- 엑세스토큰이 없는 경우에 리프레시 토큰을 체크하도록 수정했습니다.
현재 모집게시글 조회 API에서만 아래와 같은 오류가 발생해 `INTERNAL_SERVER_ERROR`를 반환하고 있어요.
찾아본 결과, 커넥션 연결 후 오랜시간 사용하지 않다가 사용하면 생기는 문제 같아요. 아무래도 connection이 오랜시간 사용되지 않아서 디비측에서 …
=> [Feature] 모집 게시글 채팅방 url 조회 API 추가

backend/src/app/user/user.controller.ts, backend/src/app/user/user.repository.ts, backend/src/app/user/user.service.ts
- 버그 내용
- 유저정보가 Promise로 Pending되어 있어서 null값인 것들도 Promise로 리턴되어서 모든 값이 모든 값이 true로 반환되어버리는 에러가 발생합니다.  
- 유저 중복 체크 실패 디버그
- async/await를 활용해 Promise를 풀어줌
=> [BUGFIX] userName 중복 확인 API

frontend/src/components/common/GroupArticleCard/index.tsx, frontend/src/components/common/GroupArticleCard/styles.ts, frontend/src/pages/index.tsx
- 모집 게시글의 title이 길어질 때, grid 규격이 깨지고 카드의 너비가 넓어지는 문제를 해결하였습니다.
- 이미지 렌더링 시 `next/Image` 를 이용해 렌더링 했습니다.
[참고 링크](https://thinkforthink.tistory.com/364)
=> [BUGFIX] 모집 게시글 카드 너비 수정

backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts, backend/src/app/group-article/dto/group-article-register-request.dto.ts, backend/src/app/group-article/dto/group-article-search-result.dto.ts, backend/src/app/group-article/group-article.controller.ts, backend/src/app/group-article/group-article.module.ts, backend/src/app/image/image.service.ts
- path 패키지를 사용하지 않고 `` 사용
- `https:/` 로 전달되었었는데 `https://`로 전달돼요.
=> [BUGFIX] 이미지 url이 제대로 전달되지 않는 문제 수정

frontend/src/pages/article/write/index.tsx
- 업로드 시 이미지 url을 전송하도록 수정했습니다
- #183
=> [BUGFIX] 게시글 썸네일 업로드시 url을 전송

backend/src/app.module.ts, backend/src/app/auth/auth.service.ts, backend/src/app/notification/constants/notification.constants.ts, backend/src/app/notification/dto/get-notification-settings-response.dto.ts, backend/src/app/notification/dto/patch-notification-setting-request.dto.ts, backend/src/app/notification/entity/notification-setting.entity.ts, backend/src/app/notification/exception/not-accessible.exception.ts, backend/src/app/notification/exception/notification-setting-not-found.exception.ts, backend/src/app/notification/notification.controller.ts, backend/src/app/notification/notification.module.ts, backend/src/app/notification/notification.service.ts, backend/src/app/notification/repository/notification-setting.repository.ts, backend/src/setSwagger.ts
- 기존에는 로그인 했을 때, 알림설정정보를 추가하지 않고 있었습니다. 추가해주었어요.
- 자신의 알림설정정보를 조회합니다
- 알림설정 변경 API 추가: 설정을 ON|OFF로 변경합니다
- 해당 설정 정보가 없는 경우 NotificationSettingNotFoundException 반환
- 자신의 설정이 아닌 경우 NotAccessibleException 반환
=> [Feature] 사용자 알림 설정 상태 수정 및 조회 API

backend/src/app/group-article/group-article.controller.ts, backend/src/app/group-article/repository/group-article.repository.ts, backend/src/common/config/database/typeorm/config.service.ts
- 내가 작성한 모집 게시글만 조회되는 API 추가
내가 작성한 모집게시글 목록조회를 위해 기존에 있던 모집게시글 목록 조회 API와 상당히 유사한 쿼리가 필요했다. 내가 작성한 모집게시글 목록페이지에는 필터링이 없고 단순히 페이지네이션만 적용된 데이터가 필요했다. 하지만 모집게시글정보에서 필요한 데이터는 같았다. 
서로 변경되는 시점이 다를 수 있을 것 같아 분리해야할까 라는 생각이 들긴하지만 우선은 하나로 합쳐놓은 상태입니다!
TypeOrm 0.2.x버전에서 0.3.x 버전으로 올라오면서 NestJS에서 TypeOrm Repository Pattern을 사용하기 위한 방법이 달라졌어요! 근데 올바르지 않은 방법으로 사용해서 생긴 문제같아요. 우선 예상되는 지점의 코드를 아래와 같이 변경해보니 로컬에서는 해결되는것 같아 올렸습니다.
https://github.com/boostcampwm-2022/web13-moyeomoyeo/blob/d5d26d5d07d30bcfc2a6f3d43d06cb66091e8955/backend/src/app/group-article/repository/group-article.repository.ts#L20-L27
정상적으로 해결된다면, 다른 repository들 유사하게 코드를 변경하거나 https://velog.io/@username1103/NestJS-TypeORM 에서 제공하는 방법2 또는 방법3 같은 방식으로 변경하면 좋을 것 같아요.
=> [Feature] 내가 작성한 모집 게시글 목록 조회

backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts, backend/src/app/group-article/dto/get-my-group-article-response.dto.ts, backend/src/app/group-article/dto/group-article-register-request.dto.ts, backend/src/app/group-article/group-article.module.ts, backend/src/app/group-article/my-group-article.controller.ts, backend/src/app/group-article/my-group-article.service.ts
- 훨씬 가독성있는 선택이라고 생각해 수정
- 내가 작성한 게시글을 조회할 때는 private한 정보(ex. 오픈채팅방url)를 전달해주어야 하기 때문에 별도 API를 제작했습니다.
- 자꾸 사람들이 모집게시글 작성 최대인원수로 능욕해서 추가했어요.
=> [Feature] 내가 작성한 모임 게시글 조회 API 추가

frontend/src/hooks/queries/useFetchGroupArticles.ts, frontend/src/pages/_app.tsx, frontend/src/pages/index.tsx
- 메인페이지에 SSR 적용 - Hydration 사용
- Hydration에서 serializing error가 발생했었습니다. 원인은 dehydrate(queryClient)의 값 중 undefined인 값이 있을 때 serializing할 수 없어 발생하는 에러로, `JSON.parse(JSON.stringify(dehydrate(queryClient)))` 를 통해 undefined 요소들을 null로 변환하여 에러를 해결했습니다.
- [프론트 성능 개선](https://brawny-zydeco-6b6.notion.site/f107179d9a2149f981c7dab4178aa11a)
=> [Feature] 메인 페이지 SSR

frontend/src/components/common/Avatar/index.tsx
- Avatar에서 ref를 전달받도록 수정했습니다.
- `Image`가 바로 ref를 받도록 해도 되지만, `next/Image`는 ref를 따로 받지 않도록 설계가 되어있어서 `div` 태그가 대신해서 Ref를 넘겨받도록 수정했습니다.
- ref를 넘겨주는 것은 React의 `forwardRef`를 이용했습니다.
```tsx
const Avatar = forwardRef<HTMLDivElement, Props>(({ size, ...rest }, ref) => {
return (
<div ref={ref}>
<AvatarImage
{...rest}
layout="fixed"
width={AVATAR_SIZES[size]}
height={AVATAR_SIZES[size]}
defaultImgUrl="/avatar.jpg"
/>
</div>
);
});
```
[forwardRef 전달하기](https://dev.to/jexperton/ref-forwarding-with-react-function-components-and-typescript-20ip)
=> [BUGFIX] 헤더상단 드랍다운 버그 해결

frontend/src/components/common/GroupArticleCard/index.tsx, frontend/src/hooks/queries/useFetchGroupArticles.ts
- GroupArticle 썸네일 이미지에 blur효과를 적용하여 로드하도록 처리하였습니다.
=> [Feature] GroupArticle 썸네일에 blur 처리

frontend/src/components/article/Comment/Comment.stories.tsx, frontend/src/components/article/Comment/index.tsx, frontend/src/components/article/Comment/styles.tsx, frontend/src/components/article/CommentInput/index.tsx, frontend/src/components/article/CommentInput/styles.tsx, frontend/src/components/common/Avatar/index.tsx, frontend/src/components/common/FloatingButton/index.tsx, frontend/src/components/common/Header/UserLoginItem/index.tsx, frontend/src/components/common/Profile/index.tsx, frontend/src/hooks/queries/useAddComment.ts, frontend/src/hooks/queries/useDeleteComment.ts, frontend/src/hooks/queries/useFetchComments.ts, frontend/src/hooks/queries/useFetchGroupArticles.ts, frontend/src/hooks/useAuthInfiniteQuery.ts, frontend/src/pages/article/[id].tsx, frontend/src/pages/index.tsx, frontend/src/pages/user/[id].tsx, frontend/src/typings/types.ts
- 무한스크롤 적용
- 댓글입력창에 내용이 있는 경우에만 버튼이 활성화
- 댓글 추가 시 댓글 목록에서 제일 아래로 이동하도록 함
- 엔터키 입력시에도 댓글이 추가되도록 대응
```tsx
const useAddComment = (articleId: number) => {
const queryClient = useQueryClient();
return useAuthMutation(addComment, {
onSuccess: async () => {
await queryClient.invalidateQueries(['article', articleId]);
await queryClient.invalidateQueries(['comments', articleId]);
},
});
};
```
- 댓글의 개수는 `/v1/group-articles/{id}`에서 조회되는 한편, 댓글의 내용들은 `/v1/comments` 에서 불러오고 있습니다.
- 이때 댓글 추가나 삭제가 발생해서 `댓글 내용 변경`과 `댓글 개수 변경`을 일으키려면 위와 같이 두 개의 쿼리를 무효화해야되는 상황이 발생합니다. 
- `['article', articleId]` 쿼리 무효화의 경우 댓글의 개수만 바뀔뿐인데 게시글 내용까지 다소 조회해야하는 다소 비효율적인 방식으로 동작합니다.
- 그래서 제 생각에는 `댓글의 총 개수`를 `/v1/comments`에 통합시켜야 되겠다라는 생각이 듭니다.
=> [Feature] 댓글 추가, 삭제, 조회 로직

frontend/src/components/common/ErrorBoundary/ApiErrorBoundary.tsx, frontend/src/components/common/ErrorMessage/index.tsx, frontend/src/hooks/useAuthInfiniteQuery.ts, frontend/src/pages/_app.tsx
- GET에러 발생 시 오픈되는 modal의 [확인 button]을 누르면 이전 페이지로 돌아가도록 했습니다.
- 기존 구현 상으로는 버튼 클릭 시 modal이 닫히도록 되어 있었습니다.
- 이 경우 알림 페이지에서 게시글 클릭 시, 해당 게시글이 삭제되어 존재하지 않는다면 modal이 열리고 확인버튼 클릭 시 modal이 닫혀 흰 화면을 보게 됩니다.
- 이런 상황에서는 확인 버튼 클릭 시 이전 페이지로 돌려보내주는 것이 좋은 방법이라 생각했습니다.
- 기존에 한 페이지 내의 특정 컴포넌트에서 GET에러가 발생했을 때, 다른 컴포넌트들은 정상적으로 렌더링시켜주기 위해 단순히 modal을 띄워 에러 상황을 알리기만 하고 다른 작업(redirect, refresh 등)은 추가하지 않았습니다. 하지만 모여모여 서비스 특성 상 보통 한 페이지 내에서 하나의 GET 요청에 대한 데이터/에러가 페이지 전체에 영향을 미치기 때문에, 굳이 컴포넌트별로 나눠 렌더링해주지 않고 이전 페이지로 돌려보내주어도 큰 문제가 없을것이라 판단했습니다.
=> [Feature] 에러 처리 - GET 에러 발생 modal

frontend/src/components/common/ArticleListLoading/index.tsx, frontend/src/components/common/ArticleViewLoading/index.tsx, frontend/src/hooks/useDeferredResponse.ts
- 짧은 로딩에 skeleton을 보여주는 것은 오히려 사용자 경험을 저하시킬 수 있습니다.
`useDeferredResponse` hook을 만들어, response가 200ms 이상 소요될 경우에만 로딩 스켈레톤이 렌더링되도록 했습니다.
[적용 전]
[적용 후]
- [링크](https://tech.kakaopay.com/post/skeleton-ui-idea/)를 통해 인사이트를 얻었습니다.
=> [Feature] 로딩 스켈레톤 딜레이 적용

frontend/src/components/common/FloatingButton/styles.tsx
- 플로팅 화면 위치를 모바일 화면 내부로 넣었습니다.
=> [Feature] 플로팅 화면 위치를 모바일 화면 안으로 넣기

backend/src/app/group-application/group-application.service.ts
- 모집완료시 마지막 참가신청자에게 알림이 가지 않는 문제해결
- 비동기 처리를 제대로 하지 않았던 것이 문제가 됐던 것 같습니다.
```typescript
private async checkGroupComplete(
groupArticle: GroupArticle,
groupApplicationCount: number,
) {
if (groupArticle.group.maxCapacity <= groupApplicationCount + 1) {
groupArticle.group.complete();
await this.groupArticleRepository.save(groupArticle);
this.eventEmitter.emit(
'group.succeed',
new GroupSucceedEvent(groupArticle),
);
}
}
```
=> [BUGFIX] 모집완료시 마지막 참가신청자에게 알림이 가지 않는 문제

frontend/src/components/common/GroupArticleCard/index.tsx, frontend/src/pages/article/[id].tsx
- 이미지 프리로딩을 적용하였습니다.
- 적용 전
- 적용 후
- 댓글 삭제 시 추가된 댓글 안보이게 수정
=> [Feature] 이미지 프리로드, 댓글 삭제시 추가된 댓글 안보이게 수정

frontend/src/components/notification/NotificationItem/NotificationItem.stories.tsx, frontend/src/components/notification/NotificationItem/index.tsx
- 사파리 및 ios에서 알림 컴포넌트가 깨지는 현상을 수정했습니다. 수정된 결과는 [여기서](https://637c707cf24ecaa36bad2e45-dcsrxqyxnc.chromatic.com/?path=/story/component-notificationitem--collection) 확인할 수 있습니다. 사파리로 들어가보세요
- 원인은 정확히 알 수 없으나 현재는 [flex 속성이 사파리 브라우저 상에서 제대로 상속되지 않는 버그](http://vnthf.logdown.com/posts/2016/10/07/safari-flex-height)가 있는 것으로 추측하고 있습니다.
- 이를 바탕으로 `NotificationWrapper`에 `display:grid`를 없애고 flex를 적용하여 상속이 제대로 이뤄지도록 했습니다.
- [사파리 flex 상속 버그](http://vnthf.logdown.com/posts/2016/10/07/safari-flex-height)
=> [BUGFIX] 사파리 알림 컴포넌트 깨짐 현상
