backend/.eslintrc.js
backend/.gitignore
backend/.husky/pre-commit
backend/.prettierrc
backend/README.md
backend/nest-cli.json
backend/package-lock.json
backend/package.json
backend/src/app.controller.spec.ts
backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/app.service.ts
backend/src/main.ts
backend/test/app.e2e-spec.ts
backend/test/jest-e2e.json
backend/tsconfig.build.json
backend/tsconfig.json

- nest 설치
- eslint, prettier 설정

[Feature] 백엔드 환경 셋팅

---

.github/workflows/backend-dev-cd.yml
backend/.gitignore
backend/docker-compose.yml
backend/scripts/dev-deploy.sh

- 백엔드 개발용 CD 추가
- 권한 문제
- 스크립트에 권한이 없어서 docker-compose를 실행시키지 못했다.
- chmod를 이용해 해당 sh파일에 권한을 부여했다.
- docker-compose 명령어를 못 찾는 문제
- 서버 환경에서 해당 의존성이 설치되지 않아 발생한 문제였다. 설치해줬다.
- docker image registry를 어떻게 쌓아가고 찾아서 사용할 것인가
- 원래 git commit hash를 이용해 tag를 구분하고 해당 태그를 사용해 도커 이미지를 registry에서 가지고 오고 있었다.
- latest와 hash tag, 이렇게 2번 registry에 등록해 docker-compose에서 이미지를 찾아올 때 latest를 사용해 가져올 이미지를 쉽게 찾을 수 있게 변경했다. 

[Feature] 백엔드 개발용 CD

---

.github/workflows/frontend-cd.yml
.github/workflows/frontend-ci.yml
frontend/Dockerfile
frontend/docker-compose.yml
frontend/scripts/dev-deploy.sh

- [] 관련된 이슈와 연결 시켰나요?
- Github actions cd 파일 구성
- frontend 도커 이미지 파일 구성
- 도커 컨테이너 구성 명령어

[Feature] 프론트엔드 CD 적용

---

.github/workflows/backend-dev-cd.yml
backend/docker-compose.local.yml
backend/docker-compose.yml
backend/scripts/dev-deploy.sh

- `backend/script/dev-devolp.sh` 수정
- linux EOF 사용법: https://shonm.tistory.com/666
- cat EOF: https://nomad-programmer.tistory.com/329

[BUGFIX] 백엔드 CD 환경변수 디버그

---

.github/workflows/frontend-cd.yml
frontend/.dockerignore
frontend/Dockerfile
frontend/Dockerfile.development
frontend/docker-compose.local.yml
frontend/docker-compose.yml
frontend/nginx.Dockerfile
frontend/nginx.conf
frontend/scripts/dev-env.sh

- Nginx 를 설정하였습니다.
- Nginx 컨테이너를 도커 컴포즈 파일에 추가했습니다.
- 문제상황과 해결 내역들은 이 [링크](https://www.notion.so/Nginx-NextJS-91c72af1706043dabdfca3c5c1aa9b47)를 참고해주세요.

[Feature] Frontend nginx 적용

---

frontend/src/components/common/PageLayout/index.tsx
frontend/src/pages/article/[id].tsx
frontend/src/pages/index.tsx

- 페이지 내에서 padding 없이 전체를 차지하는 요소도 있으므로, 각 페이지 내에서 padding을 주도록 함

[Fix] 페이지 content 전체 padding 제거

---

frontend/src/pages/login.tsx
frontend/src/styles/GlobalStyles.tsx

- #82 을 해결하기 위해 로그인 페이지의 높이를 조정했습니다.
- #83 을 해결하기 위해 전역으로 폰트 설정을 했습니다.

[Fix] 로그인페이지 이슈 / 로컬 폰트 적용 이슈 해결

---

.github/workflows/backend-dev-cd.yml
backend/.dockerignore
backend/dev/nginx/nginx.conf
backend/scripts/dev-deploy.sh

백엔드 cd가 정상적으로 이루어지지 않는 문제가 있어 수정했습니다.
ssl인증서가 없는데 ssl 설정이 되어있고, 리다이렉트 시켜 정상적 접근이 불가능함.
1. nginx ssl 제거
2. nginx upstream이 ip주소로 되어있던 부분을 컨테이너 이름으로 변경
환경변수가 제대로 추가되지 않아 서버 컨테이너 속 서버가 켜지지 않는 문제 
1. 서버 이미지 생성시 `.env.development` 파일을 생성해 카피될 수 있도록 수정

[FIX] 백엔드 CD 수정

---

frontend/src/components/common/Profile/Profile.stories.tsx
frontend/src/components/common/Profile/index.tsx
frontend/src/constants/dummy.ts
frontend/src/constants/pageTitle.ts
frontend/src/pages/my.tsx
frontend/src/pages/user/[id].tsx

- 프로필 공통 컴포넌트 생성
- 유저 프로필 페이지 마크업
- 마이페이지 마크업

[Feature] 프로필 페이지 마크업

---

frontend/src/components/common/ErrorMessage/ErrorMessage.stories.tsx
frontend/src/components/common/ErrorMessage/index.tsx
frontend/src/constants/error.ts
frontend/src/pages/404.tsx
frontend/src/pages/500.tsx

- `ErrorMessage` 공통 컴포넌트 생성
- 404, 500 페이지 생성

[Feature] 404, 500 에러 페이지

---

frontend/next.config.js
frontend/src/apis/test/getTestMyData.ts
frontend/src/constants/dummy.ts
frontend/src/hooks/queries/useFetchMyData.ts
frontend/src/mocks/handlers.ts
frontend/src/mocks/resolvers/getMyInfo.ts
frontend/src/pages/_app.tsx
frontend/src/pages/article/write/index.tsx
frontend/src/pages/my/edit.tsx

- Mock API와 연동하여 자기 정보를 불러오도록 설정
- react-query 설정
- 데이터 패칭 함수 추가
- Mock API 추가 
- 닉네임, 깃허브 링크가 비어있지는 않은지 검사
- 닉네임은 10자 내로 적었는지 검사
- 한 줄 소개란은 20자 내외로 썼는지 검사
- next에서 Github에 호스팅된 이미지를 불러올 수 있도록 설정 추가

[Feature] 프로필 수정 페이지 마크업

---

.github/workflows/frontend-cd.yml
frontend/docker-compose.yml
frontend/scripts/dev-deploy.sh

- nginx 설정 도커 컴포즈에 적용
- Next 캐싱을 위한 Nginx 설정이 쉽지 않았다.
- `/etc/nginx/nginx.conf`와 `/etc/nginx/conf.d`를 둘 다 설정해 문제를 해결!
```yaml
nginx:
container_name: nginx
image: nginx
ports:
- 80:80
- 443:443
volumes:
- ./dev/default/nginx.conf:/etc/nginx/nginx.conf
- ./dev/nginx:/etc/nginx/conf.d
- /letsencrypt/certbot/conf:/etc/letsencrypt
- /letsencrypt/certbot/www:/var/www/certbot
depends_on:
- frontend
networks:
- backbone
```

[BugFix] 프론트엔드 HTTPS 배포

---

backend/src/app.module.ts
backend/src/app/auth/auth.controller.ts
backend/src/app/auth/auth.module.ts
backend/src/app/group-article/group-article.controller.ts
backend/src/app/group-article/group-article.module.ts
backend/src/app/myinfo/myinfo.module.ts
backend/src/app/user/user.module.ts
backend/src/common/config/cookie/config.module.ts
backend/src/common/config/cookie/config.service.ts
backend/src/common/config/cookie/configuration.ts
backend/src/common/guard/jwt-auth.guard.ts
backend/src/common/module/jwt-token/jwt-token.module.ts

- 쿠키 secure옵션을 환경변수를 통해 지정될 수 있도록 했습니다. 환경변수 SECURE=true인 경우에 쿠키에 secure, sameSite=none 옵션이 추가됩니다
- JwtAuthGuard를 사용하기 위해 모듈을 import해야하는 번거로움이 있어 사용되는 서비스를 포함한 모듈을 global로 설정해주었습니다.

[Feature] 쿠키 옵션 설정 수정

---

backend/src/app/myinfo/dto/myinfo-get-response.dto.ts
backend/src/app/user/__test__/user.fixture.ts
backend/src/app/user/dto/nickname-unique-request.dto.ts
backend/src/app/user/dto/user-info-response.dto.ts
backend/src/app/user/dto/username-unique-request.dto.ts
backend/src/app/user/dto/username-unique-response.dto.ts
backend/src/app/user/entity/user.entity.ts
backend/src/app/user/exception/user-not-found.exception.ts
backend/src/app/user/user.controller.ts
backend/src/app/user/user.repository.ts
backend/src/app/user/user.service.ts

- 다른 사용자 정보 조회 API
- swagger 작성
- API 명세와 Response가 동일하지 않음을 발견
- 코드의 `username`을 명세에 맞게 `userName`으로 변경

[Feature] 다른 사용자 정보 조회하기 API

---

backend/src/app/group-article/constants/group-article.constants.ts
backend/src/app/group-article/dto/group-article-register-request.dto.ts
backend/src/app/group-article/entity/article.entity.ts
backend/src/app/group-article/entity/group-article.entity.ts
backend/src/app/group-article/entity/group.entity.ts
backend/src/app/group-article/group-article.controller.ts
backend/src/app/group-article/group-article.service.ts
backend/src/app/group-article/repository/group-article.repository.ts
backend/src/setSwagger.ts

- 게시글 엔티티에 유저 연관관계 설정
- 모집 게시글 생성시 유저정보 추가하도록 수정
- enum 클라이언트와 일관성을 위해 영어로 수정
```
{
"title": "CS 스터디 모집",
"contents": "\n      안녕하세요. 서울 지역 CS 스터디원들을 모집합니다!\n      <img width=\"1440\" alt=\"서울 지역 CS 모집 사진자료\" src=\"https://kr.object.ncloudstorage.com/moyeo-images/uploads/images/1669282011949-761671c7-cc43-4cee-bcb5-4bf3fea9478b.png\">\n      ",
"category": "STUDY",
"location": "ONLINE",
"maxCapacity": 10,
"thumbnail": "https://kr.object.ncloudstorage.com/moyeo-images/uploads/images/1669282011949-761671c7-cc43-4cee-bcb5-4bf3fea9478b.png",
"chatUrl": "https://open.kakao.com/오픈채팅방path"
}
```
```
{
"status": "OK",
"message": "",
"data": {
"totalPage": 2,
"currentPage": 1,
"countPerPage": 10,
"data": [
{
"id": 16,
"title": "CS 스터디 모집",
"thumbnail": {
"key": …
```

[Fix] 모집 게시글 작성 API 수정 

---

backend/src/app/group-article/entity/group-article.entity.ts
backend/src/app/group-article/exception/group-article-not-found.exception.ts
backend/src/app/group-article/exception/not-author.exception.ts
backend/src/app/group-article/group-article.controller.ts
backend/src/app/group-article/group-article.service.ts

모집 게시글 삭제 API 추가했습니다. 작성자가 아닌 경우 NotAuthorException을 반환하고 해당하는 게시글이 존재하지 않는 경우 GroupArticleNotFoundException을 반환합니다.

[Feature] 모집 게시글 삭제 API

---

backend/src/app/image/image.controller.ts

- 이미지 업로드 Swagger Body 내용 추가
- 배열 형태의 자료형을 `@ApiBody`에 넣는 것이 힘들었다. <s>결국 명일 선생님의 도움을..</s>
- Swagger JSDocs과 비슷하게 구성하면 된다!
- [이미지 업로드](https://velog.io/@hahaha/NestJS-%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C%ED%95%98%EA%B8%B0)
- [Swagger JSDocs 정리](https://lahuman.github.io/nodejs_swagger/)

[Feature] 이미지 업로드 Swagger 보충

---

backend/src/app/group-article/dto/author.dto.ts
backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts
backend/src/app/group-article/dto/group-article-detail.interface.ts
backend/src/app/group-article/dto/group-article-search-result.dto.ts
backend/src/app/group-article/exception/group-article-not-found.exception.ts
backend/src/app/group-article/group-article.controller.ts
backend/src/app/group-article/group-article.service.ts
backend/src/app/group-article/repository/group-article.repository.ts
backend/src/common/dto/image-response.dto.ts

상세 모집 게시글 조회 API를 추가했습니다.
응답 객체
```
{
"status": "OK",
"message": "",
"data": {
"id": 1,
"title": "CS 스터디 모집",
"content": "안녕하세요. 서울 지역 CS 스터디원들을 모집합니다!\\n<img width=\"1440\" alt=\"서울 지역 CS 모집 사진자료\" src=\"https://kr.object.ncloudstorage.com/moyeo-images/uploads/images/1669282011949-761671c7-cc43-4cee-bcb5-4bf3fea9478b.png\">",
"author": {
"id": 1,
"userName": "박종혁",
"profileImage": "https://avatars.githubusercontent.com/u/67570061?v=4"
},
"category": {
"id": 1,
"name": "스터디"
},
"location": "ONLINE",
"thumbnail": {
"key": "1669276833875-64adca9c-94cd-4162-a53f-f75e951e39db",
"url": "https://kr.object.ncloudstorage.com/uploads/images/1669276833875-64adca9c-94cd-4162-a53f-f75e951e39db"
},
"status": "PROGRESS",
"commentCount": 10,
"scrapCount": 12,
"maxCapacity": 10,
"createdAt": …
```

[Feature] 모집 게시글 상세조회 API 제작

---

.github/workflows/frontend-cd.yml
.github/workflows/frontend-ci.yml
frontend/Dockerfile
frontend/scripts/dev-deploy.sh
frontend/src/components/login/GitLoginButton/index.tsx

- #144 를 참고해주세요
- [build-push 액션에 secret값 넘기기](https://dev.to/jpoehnelt/environment-variables-in-github-docker-build-push-action-23pj)
- [Dockerfile에서 ENV 사용하기](https://hulint.tistory.com/42)

[Feature] Dockerfile에 환경 변수 주입

---

.github/workflows/frontend-cd.yml
.github/workflows/frontend-ci.yml
backend/.gitignore
backend/src/setNestApp.ts
frontend/next.config.js
frontend/scripts/dev-deploy.sh
frontend/src/components/login/GitLoginButton/index.tsx
frontend/src/hooks/queries/useFetchMyInfo.ts

#147 을 해결하였음
- credential option 추가

[Feature] credential 옵션 추가

---

backend/src/app/group-application/dto/check-joining-group-response.dto.ts
backend/src/app/group-application/dto/group-application-request.dto.ts
backend/src/app/group-application/entity/group-application.entity.ts
backend/src/app/group-application/group-application.controller.ts
backend/src/app/group-application/group-application.service.ts
backend/src/app/group-article/entity/group-article.entity.ts

[Feature] 모임 신청 여부 조회 API

---

backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts
backend/src/app/group-article/dto/group-article-register-request.dto.ts
backend/src/app/group-article/dto/group-article-search-result.dto.ts
backend/src/app/group-article/entity/group-article.entity.ts
backend/src/app/group-article/entity/group.entity.ts
backend/src/app/group-article/group-article.controller.ts
backend/src/app/group-article/group-article.service.ts
backend/src/app/group-article/repository/group-category.repository.ts

- 작성자가 아니면 NotAuthorException 반환
- 모집중인 게시글이 아니면 NotProgressGroupException 반환
- 모집게시글이 존재하지 않으면 GroupArticleNotFoundException 반환
- 유효한 모집게시글을 모집중단 상태로 변경한다.
`typeorm`에서 `deletedAt`이 `null`인 게시글만 가져오기 위해 아래와 같이 사용했지만 제대로 쿼리가 나가지 않았다.
```
this.findOneBy({ deletedAt: null })
```
typeorm에서 제공해주는 `IsNull()`을 사용한 쿼리로 변경하여 원하는 쿼리가 생성되도록 했다.
```
this.findOneBy({ deletedAt: IsNull() })
```
```
{
"status": "OK",
"message": "",
"data": {
"id": 1,
"title": "CS 스터디 모집",
"content": "안녕하세요. 서울 지역 CS 스터디원들을 모집합니다!\\n<img width=\"1440\" alt=\"서울 지역 CS 모집 사진자료\" src=\"https://kr.object.ncloudstorage.com/moyeo-images/uploads/images/1669282011949-761671c7-cc43-4cee-bcb5-4bf3fea9478b.png\">",
"author": {
"id": 1,
"userName": "박종혁",
"profileImage": "https://avatars.githubusercontent.com/u/67570061?v=4"
}, …
```

[Feature] 모집 중단 API 추가

---

backend/src/app/image/image.controller.ts
backend/src/app/image/image.service.ts

- 작업한 내용을 간략하게 작성해주세요.
- `aws-sdk`의 메소드 내에서 Error 처리를 그냥 하려고 했는데 서버가 그냥 터져버리는 문제가 발생했다.
- 필터에서 에러를 감지하지 못함 
- Promise로 감싸서 해결!
- 필터에 감지되도록 에러가 기다리도록 만들었다. 

[BUGFIX] 이미지 업로드 예외처리

---

backend/src/app/group-application/group-application.controller.ts

- API 명세 변경으로 인한 수정
- POST => GET
- Body => Query String

[Feature] 명세 변경으로 인한 신청 여부 조회 API 수정

---

frontend/src/hooks/queries/useFetchProfile.ts
frontend/src/pages/user/[id].tsx

- 다른 유저 프로필 조회 API 연결하였습니다.
- 본인 프로필 조회는 다른 이슈에서 처리완료되었습니다. https://github.com/boostcampwm-2022/web13-moyeomoyeo/pull/135

[Feature] 유저 프로필 조회 API 연결

---

backend/src/app.module.ts
backend/src/app/comment/comment.controller.ts
backend/src/app/comment/comment.module.ts
backend/src/app/comment/comment.repository.ts
backend/src/app/comment/comment.service.ts
backend/src/app/comment/dto/comment-writing-request.dto.ts
backend/src/app/comment/dto/comment-writing-response.dto.ts
backend/src/app/comment/entity/comment.entity.ts
backend/src/app/comment/exception/group-not-found.exception.ts
backend/src/app/group-application/group-application.service.ts
backend/src/setSwagger.ts

[Feature] 모집 게시글 댓글 작성 API

---

frontend/src/components/common/EmptyMessage/index.tsx
frontend/src/components/notification/NotificationIcon/index.tsx
frontend/src/components/notification/NotificationItem/NotificationItem.stories.tsx
frontend/src/components/notification/NotificationItem/index.tsx
frontend/src/constants/notification.ts
frontend/src/pages/notification.tsx
frontend/src/typings/types.ts

- 레이아웃 구성하기
- 닫기 버튼 클릭 시 알림 삭제 확인 모달 표시
- 알림 컨텐츠 부분 클릭시 해당 게시글로 이동
- 알림 조회, 삭제 API 연동하기
- 게시글 아이디랑 연결 짓기
- 삭제 버튼 클릭 후 확인시 해당 알림 삭제

[Feature] 알림 컴포넌트, 페이지 마크업

---

frontend/src/components/common/ArticleLoading/index.tsx
frontend/src/hooks/useAuthQuery.ts
frontend/src/hooks/useGeneralQuery.ts
frontend/src/pages/article/[id].tsx
frontend/src/pages/user/[id].tsx

- `useRouter`에서 query.id가 `undefined` 라서 제대로된 query를 생성하지 못하는 버그 수정
- 게시글 상세 조회에서 로딩바를 추가하여 빈 화면이 보이지 않게 함

[BUGFIX] 게시글 상세 조회시 NaN 요청 보내는 문제 해결

---

backend/src/app/comment/comment.controller.ts
backend/src/app/comment/comment.repository.ts
backend/src/app/comment/comment.service.ts
backend/src/app/comment/entity/comment.entity.ts
backend/src/app/comment/exception/comment-not-found.exception.ts
backend/src/app/comment/exception/not-author.exception.ts
backend/src/app/myinfo/dto/profile-modifying-request.dto.ts

- 댓글 삭제 API 작성
- 댓글이 존재하는지 확인
- 댓글 작성자인지 확인

[Feature] 모집 게시글 댓글 삭제 API 

---

backend/src/app/group-article/dto/get-group-chat-url-response.dto.ts
backend/src/app/group-article/dto/get-my-group-article-response.dto.ts

채팅 url값을 `url` -> `chatUrl`로 통일

[Feature] 채팅 url을 chatUrl로 통일

---

backend/src/app/group-application/exception/closed-group.exception.ts
backend/src/app/group-application/group-application.controller.ts
backend/src/app/group-application/group-application.repository.ts
backend/src/app/group-application/group-application.service.ts

- 인원 제한 exception
- 꽉차면 자동으로 상태 변경
- 모집 중에만 참가신청할 수 있도록 exception
- 모집 완료되면 알림 송신

[Feature] 모집 API 예외처리 추가 및 알림달기

---

backend/src/app/notification/entity/user-notification.entity.ts
backend/src/app/notification/exception/user-notification-not-found.exception.ts
backend/src/app/notification/notification.controller.ts
backend/src/app/notification/notification.service.ts

- 알림이 존재하지 않는 경우 UserNotificationNotFoundException 반환
- 자신의 알림이 아닌 경우 NotAccessibleException 반환
- 유효한 경우, 해당 알림을 soft delete

[Feature] 알림 삭제 API 추가

---

frontend/src/components/article/ParticipantsModal/ParticipantItem/index.tsx
frontend/src/components/article/ParticipantsModal/index.tsx
frontend/src/components/article/ParticipateButton/ApplyButton/index.tsx
frontend/src/components/article/ParticipateButton/CancelButton/index.tsx
frontend/src/constants/dummy.ts
frontend/src/hooks/queries/useApplyGroup.ts
frontend/src/hooks/queries/useCancelApplication.ts
frontend/src/hooks/queries/useFetchApplicationStatus.ts
frontend/src/hooks/queries/useFetchArticle.ts
frontend/src/hooks/queries/useFetchParticipants.ts
frontend/src/pages/article/[id].tsx
frontend/src/pages/user/[id].tsx
frontend/src/typings/types.ts

- 참가 신청자 목록 api 연결
- 신청자 아이템 우측 아이콘 클릭 시 유저페이지로 이동
- 참가 신청/취소 시 신청자 목록 invalidate
- 게시글 내 author Avatar 클릭 시 유저페이지로 이동
- 참가 신청/취소 버튼 클릭 시 `confirm modal` open
- 모집 인원이 다 찼을 경우 하단 버튼 비활성화
- 유저페이지에서 `isReady` undefined로 들어와 `로딩중` 만 보이던 버그 해결

[Feature] 신청자 목록 조회

---

backend/src/app/auth/auth.controller.ts
backend/src/app/group-application/group-application.service.ts

- 쿠키 삭제
- 로그아웃 API 작성
- JWT 쿠키 삭제

[Feature] 로그아웃 API

---

backend/package-lock.json
backend/package.json
backend/src/app/group-application/dto/group-article-response.dto.ts
backend/src/app/group-application/group-application.service.ts

- thumbnail: string -> thumbanil: { originUrl: string, blurUrl: string } 으로 변경

[Feature] 내가 참여한 모임 thumbnail response 수정

---

backend/src/app/comment/comment.repository.ts
backend/src/app/notification/entity/notification.entity.ts
backend/src/app/notification/notification.listener.ts
backend/src/app/notification/repository/user-notification.repository.ts

- 메시지 양식 변경
- subTitle: "메시지 내용" => "유저이름: 메시지 내용" 
- 본인이 쓴 댓글에 알림이 오지 않도록 설정을 변경

[BUGFIX] 내가 작성한 댓글에 대해 알림이 오는 문제

---

backend/src/app/comment/comment.controller.ts
backend/src/app/comment/comment.service.ts
backend/src/app/comment/dto/comment-writing-response.dto.ts

- 불필요한 async 제거
- 아래의 async를 제거해줌
- response return이 빠져있어서 추가

[BUGFIX] Group Not Found Exception 서버 에러

---

backend/src/app/group-application/dto/group-article-response.dto.ts
backend/src/app/group-application/group-application.repository.ts
backend/src/app/group-article/__test__/group-article.fixture.ts

- Internal Error 해결
- 결과가 없을 시 빈 배열 반환
- API 명세 변경에 따른 DTO 변경

[BUGFIX] 참여한 모집 게시글 목록 조회 500에러 발생

---

backend/src/common/util/page-result.ts

[Feature] limit, offset 페이지네이션 방식에서 전체 개수 전달하기

---

frontend/src/components/common/Image/index.tsx

- 프로필 이미지 첨부시 썸네일에 첨부된 이미지가 보이도록 반영

[BUGFIX] 프로필 이미지 변경 대응

---

frontend/src/pages/article/[id].tsx

- 내가 신청한 모임이 성사되었을 때, [오픈채팅방 링크 복사] 버튼이 떠야하는데 [모집마감] 버튼이 보이는 문제를 해결했습니다.
- 원래 잘 됐는데 언제 버그가 생긴건지는 잘 모르겠어요...ㅠㅠ

[Bugfix] 오픈채팅방 링크버튼 대신 모집마감 버튼이 뜨는 버그 해결

---

backend/src/app/notification/notification.listener.ts

- 게시물 작성자에게도 댓글 알림이 가도록 설정
- 알림 타겟에 게시글 작성자도 추가함
```typescript
const targetUsers =
await this.notificationSettingRepository.findTargetUsers({
type: NOTIFICATION_SETTING_TYPE.COMMENT,
userIds: commentList
.map((comment) => comment.userId)
.concat(groupArticle.userId),
});
```

[Feature] 게시물 작성자에게도 댓글 알림이 가도록 설정

---

backend/test/group-application.e2e-spec.ts

- 테스트 케이스
- 정상 실행 시
- 신청자가 작성자만 있을 때
- 본인이 신청하고 본인이 조회할 때
- 2명 이상의 유저가 신청한 게시글의 참가신청자를 조회할 때
- JWT 토큰이 없을 때
- 해당 그룹이 존재하지 않을 때

[Feature] Group Application - 참가 신청자 조회 API Test

---

.github/workflows/backend-dev-cd.yml
.github/workflows/backend-dev-ci.yml
.github/workflows/frontend-cd.yml
.github/workflows/frontend-ci.yml
.github/workflows/slack-notification.yml
backend/Dockerfile
frontend/Dockerfile
frontend/Dockerfile.development

- CI 캐싱 이용해서 의존성 설치시간 단축하기
- 저장소를 삭제하고 클론받는 것이 아닌 Docker file, config, Docker Compose만으로 CD 진행하기
- 정리한 자료: https://rural-sunscreen-ad9.notion.site/Github-Actions-CI-CD-486f3b6a148742cc8f42525f88d090c7

[Feature] CI/CD 최적화

---

.github/workflows/backend-prod-cd.yml
.github/workflows/backend-prod-ci.yml
backend/docker-compose.local.yml
backend/docker-compose.prod.yml
backend/docker-compose.yml
backend/scripts/prod-deploy.sh

- Production 배포 CI/CD
- tag 붙이기 자동화

[Feature] 백엔드 Production 배포 Test PR

---

.github/workflows/backend-prod-cd.yml

🥅 chore: head commit test 0.0.2

---

.github/workflows/backend-prod-cd.yml

Production tag PR Test

---

.github/workflows/backend-prod-cd.yml

Production CD PR Test

---

.github/workflows/backend-prod-cd.yml

Production PR Test 0.0.5

---

backend/docker-compose.local.yml
backend/docker-compose.prod.yml
backend/docker-compose.yml
backend/init-letsencrypt.sh
backend/scripts/prod-deploy.sh

Production PR Test 0.0.6

---

backend/docker-compose.prod.yml

Production PR Test 0.0.7

---

.github/workflows/backend-prod-cd.yml

Production PR Test 0.0.8

---

.github/workflows/backend-prod-cd.yml

Production PR Test 0.0.9

---

backend/docker-compose.prod.yml
backend/package.json

Production PR Test 0.0.10

---

.github/workflows/backend-prod-cd.yml

Production PR Test 0.0.12

---

frontend/src/components/article/Comment/index.tsx
frontend/src/components/article/CommentInput/CommentInput.stories.tsx
frontend/src/components/article/CommentInput/index.tsx
frontend/src/hooks/queries/useAddComment.ts
frontend/src/hooks/queries/useDeleteComment.ts
frontend/src/hooks/queries/useFetchComments.ts
frontend/src/pages/article/[id].tsx
frontend/src/typings/types.ts

- 댓글의 총개수를 기존의 게시글 쿼리에서 가져오는 것을 대체하여 댓글쿼리 에서 가져오도록 합니다.
- 댓글 추가시 상단에 추가된 댓글이 있음을 알려줍니다.
- 댓글의 현재개수가 5개 이하일때는 추가된 댓글을 보여주는 대신 스크롤을 내려줍니다
- 댓글의 현재개수가 5개 초과일때는 추가된 댓글을 보여주도록 합니다.
- 댓글 삭제시엔 추가된 댓글 표시창을 없앱니다.
이는 이렇게 조치하지 않을 경우 아래와 같이 댓글이 다 삭제해도 새로 추가한 댓글이 표시되는 현상이 생기기 때문입니다.

[Feature] 댓글 추가시 상단에 추가된 댓글 표시

---

frontend/src/components/common/NotificationLoading/NotificationLoading.tsx
frontend/src/components/common/ProfileLoading/ProfileLoading.tsx
frontend/src/hooks/queries/useFetchNotifications.ts
frontend/src/pages/article/edit/[id].tsx
frontend/src/pages/notification.tsx
frontend/src/pages/user/[id].tsx

- 게시글 수정 로딩중 처리
- 데이터 로딩중엔 form에 `undefined` 값이나 0으로 채움
- 유저 프로필페이지 로딩중 스켈레톤 처리
- notification 페이지 스켈레톤 처리

[Feature] 로딩중 스켈레톤 적용

---

backend/src/main.ts
backend/src/setNestApp.ts
backend/src/setSwagger.ts

- 개발용 서버에서만 Swagger가 호스팅 되도록 했습니다.
- `https://dev.moyeomoyeo.com` 을 추가했습니다.
- 개발용 서버에서는 지금처럼 그대로 모든 Origin을 허용하도록 했습니다.
- 프로덕션 서버에서는 `https://www.moyeomoyeo.com` 만 허용했습니다.

[Feature] 환경에 따른 CORS, Swagger 처리

---

backend/src/app/group-article/dto/group-article-register-request.dto.ts
backend/test/group-article.e2e-spec.ts

- e2e 테스트 코드 작성
- 모집 게시글 생성 POST /group-articles
- 모집 게시글 수정 PUT /group-articles/:id
- 모집 게시글 모집 완료 POST /group-articles/:id/recruitment-complete
- 모집 게시글 모집 중단 POST /group-articles/:id/recruitment-cancel
- 모집게시글 카테고리 조회 GET /group-articles/categories
- 모집 게시글 단일 조회 GET /group-articles/:id
- 모집 게시글 리스트 조회 GET /group-articles/search?category=스터디&location=서울&status=모집중
- 모집 게시글 채팅방 URL 조회 GET /group-articles/:id/chat-url
- 모집 게시글 삭제 DELETE /group-articles/:id
<br/>
- group-application과 group-article API를 테스트하는 시간 총 40초
- Group Article만 e2e 테스트를 돌리는데 23초라는 긴 시간이 걸린다.
- CI에서 e2e 테스트를 수행하면 55초나 걸린다.
- 테스트 시간을 줄일 수 있는 방법을 찾아봐야할 것 같다.
<br/>

[Feature] Group Article API Test 코드 작성
